/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author danny
 */
public class telaClientes extends javax.swing.JFrame {

    /**
     * Creates new form telaClientes
     */
    public telaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtSalvar = new javax.swing.JButton();
        jBtInserir = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jTxtCasaCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLblNrBiCliente = new javax.swing.JLabel();
        jLblSexoCliente = new javax.swing.JLabel();
        jLblNomeCliente = new javax.swing.JLabel();
        jLblCasaCliente = new javax.swing.JLabel();
        jTxtNomeCliente = new javax.swing.JTextField();
        jTxtNrBiCliente = new javax.swing.JTextField();
        jLblBairroCliente = new javax.swing.JLabel();
        jTxtBairroCliente = new javax.swing.JTextField();
        jTxtQuarteiraoCliente = new javax.swing.JTextField();
        jLblQuarteiraoCliente = new javax.swing.JLabel();
        jBtnSalvarImagem = new javax.swing.JButton();
        jBtnUploadImagem = new javax.swing.JButton();
        jTxtUploadImagem = new javax.swing.JTextField();
        jLblRecebeImagem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLblContactoCliente1 = new javax.swing.JLabel();
        jTxtContactoCliente1 = new javax.swing.JTextField();
        jRBMasculino = new javax.swing.JRadioButton();
        jRBFemenino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setMinimumSize(new java.awt.Dimension(850, 600));
        setPreferredSize(new java.awt.Dimension(850, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Cadastro de Clientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 420, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/customer_person_people_man_you_1625(2).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 80));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, 100));

        jBtSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        jBtSalvar.setText("Salvar");
        jBtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 60));

        jBtInserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"))); // NOI18N
        jBtInserir.setText("Inserir");
        getContentPane().add(jBtInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, 60));

        jBtExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jBtExcluir.setText("Excluir");
        getContentPane().add(jBtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 160, 60));

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtCancelar.setText("Cancelar");
        getContentPane().add(jBtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 60));

        jTxtCasaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCasaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtCasaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 80, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 590, 150));

        jLblNrBiCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblNrBiCliente.setText("Nr B.I :");
        getContentPane().add(jLblNrBiCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 110, 20));

        jLblSexoCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblSexoCliente.setText("Sexo :");
        getContentPane().add(jLblSexoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, 20));

        jLblNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblNomeCliente.setText("Nome :");
        getContentPane().add(jLblNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 110, 20));

        jLblCasaCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblCasaCliente.setText("Casa:");
        getContentPane().add(jLblCasaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 50, 30));
        getContentPane().add(jTxtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 220, 30));
        getContentPane().add(jTxtNrBiCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 220, 30));

        jLblBairroCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblBairroCliente.setText("Bairro:");
        getContentPane().add(jLblBairroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, -1));

        jTxtBairroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBairroClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtBairroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 220, 30));

        jTxtQuarteiraoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuarteiraoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtQuarteiraoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 70, 30));

        jLblQuarteiraoCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblQuarteiraoCliente.setText("Quart:");
        getContentPane().add(jLblQuarteiraoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 50, 30));

        jBtnSalvarImagem.setText("Salvar");
        jBtnSalvarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarImagemActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalvarImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 160, 20));

        jBtnUploadImagem.setText("Upload");
        getContentPane().add(jBtnUploadImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 70, 20));
        getContentPane().add(jTxtUploadImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 120, 30));
        getContentPane().add(jLblRecebeImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 190, 120));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Imagem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 240, 210));

        jLblContactoCliente1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblContactoCliente1.setText("Contacto:");
        getContentPane().add(jLblContactoCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 110, -1));

        jTxtContactoCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtContactoCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtContactoCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 220, 30));

        jRBMasculino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBMasculino.setText("Masculino");
        jRBMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMasculinoActionPerformed(evt);
            }
        });
        getContentPane().add(jRBMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jRBFemenino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBFemenino.setText("Feminino");
        getContentPane().add(jRBFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalvarActionPerformed
        // TODO add your handling code here:
//        if(){
//            
//        }
        String nrBi = jTxtNrBiCliente.getText();
        String nome = jTxtNomeCliente.getText();
        String contacto = jTxtContactoCliente1.getText();
        int nrCasa = Integer.parseInt(jTxtCasaCliente.getText());
        int nrQuateirao = Integer.parseInt(jTxtQuarteiraoCliente.getText());
        String bairro = jTxtBairroCliente.getText();
        
    }//GEN-LAST:event_jBtSalvarActionPerformed

    private void jTxtCasaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCasaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCasaClienteActionPerformed

    private void jTxtBairroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBairroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBairroClienteActionPerformed

    private void jTxtQuarteiraoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuarteiraoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuarteiraoClienteActionPerformed

    private void jBtnSalvarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSalvarImagemActionPerformed

    private void jTxtContactoCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtContactoCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtContactoCliente1ActionPerformed

    private void jRBMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBMasculinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new telaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtInserir;
    private javax.swing.JButton jBtSalvar;
    private javax.swing.JButton jBtnSalvarImagem;
    private javax.swing.JButton jBtnUploadImagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblBairroCliente;
    private javax.swing.JLabel jLblCasaCliente;
    private javax.swing.JLabel jLblContactoCliente1;
    private javax.swing.JLabel jLblNomeCliente;
    private javax.swing.JLabel jLblNrBiCliente;
    private javax.swing.JLabel jLblQuarteiraoCliente;
    private javax.swing.JLabel jLblRecebeImagem;
    private javax.swing.JLabel jLblSexoCliente;
    private javax.swing.JRadioButton jRBFemenino;
    private javax.swing.JRadioButton jRBMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtBairroCliente;
    private javax.swing.JTextField jTxtCasaCliente;
    private javax.swing.JTextField jTxtContactoCliente1;
    private javax.swing.JTextField jTxtNomeCliente;
    private javax.swing.JTextField jTxtNrBiCliente;
    private javax.swing.JTextField jTxtQuarteiraoCliente;
    private javax.swing.JTextField jTxtUploadImagem;
    // End of variables declaration//GEN-END:variables
}
