/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.CardLayout;

/**
 *
 * @author danny
 */
public class telaAjuda extends javax.swing.JFrame {

    /**
     * Creates new form ajuda
     */
    public telaAjuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SIGEFAPO  -  AJUDA  AO  USUARIO");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bootloader_users_person_people_6080.png"))); // NOI18N
        jLabel1.setToolTipText("Clientes");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dinheiro.png"))); // NOI18N
        jLabel2.setToolTipText("Pagamentos");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios.png"))); // NOI18N
        jLabel3.setToolTipText("Relatorios");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel5.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contrato.png"))); // NOI18N
        jLabel4.setToolTipText("Contratos");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel6.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/process_accepting_2340.png"))); // NOI18N
        jLabel5.setToolTipText("Configuracoes");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel7.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);

        jPanel9.setLayout(new java.awt.CardLayout());

        jPanel10.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel10.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10, "card2");

        jPanel11.setLayout(new java.awt.BorderLayout());

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel11.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11, "card3");

        jPanel12.setLayout(new java.awt.BorderLayout());

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel12.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel12, "card4");

        jPanel13.setLayout(new java.awt.BorderLayout());

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jPanel13.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel13, "card5");

        jPanel14.setLayout(new java.awt.BorderLayout());

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        jPanel14.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel14, "card6");

        jScrollPane1.setViewportView(jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
         CardLayout ver = (CardLayout)jPanel9.getLayout();
        ver.show(jPanel9, "card2");
        jTextArea1.setText("             <h1>hafkjhbhrj</h1>\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h1>hafkjhbhrj</h1>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h1>hafkjhbhrj</h1>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n");
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        CardLayout ver = (CardLayout)jPanel9.getLayout();
        ver.show(jPanel9, "card3");
        jTextArea2.setText("             <h2>hafkjhbhrj</h2>\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h2>hafkjhbhrj</h2>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h1>hafkjhbhrj</h1>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n");
    
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        CardLayout ver = (CardLayout)jPanel9.getLayout();
        ver.show(jPanel9, "card4");
        jTextArea3.setText("             <h3>hafkjhbhrj</h3>\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h3>hafkjhbhrj</h3>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h1>hafkjhbhrj</h1>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n");
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        CardLayout ver = (CardLayout)jPanel9.getLayout();
        ver.show(jPanel9, "card5");
        jTextArea4.setText("             <h4>hafkjhbhrj</h4>\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h4>hafkjhbhrj</h4>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h1>hafkjhbhrj</h1>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n");
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        CardLayout ver = (CardLayout)jPanel9.getLayout();
        ver.show(jPanel9, "card6");
        jTextArea5.setText("             <h5>hafkjhbhrj</h5>\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h5>hafkjhbhrj</h5>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n"
                            + "</br>sbfhjbrshuhsnakskjhhnjsnkjhrfssvjkdfhhb\n"
                            + "vnjskdndfvklngskjngfjngdfjgndkgnkgfklnmkgf\n\n"
                            + "             <h1>hafkjhbhrj</h1>\n"
                            + "khbjfdxnvkjndlkvnjdkjvfknsdshkvjbhkjbnzdfkj.\n"                
                            + "fkdjjb,vfdjbvkdjbfvhbvukjnbvjbnbkbdfbjfb,fdz\n"
                            + "fdjhskbvjdfkjsnvjkdfnskjjknsdfk jn fnjklnflkj\n"
                            + "jhkbjkhvfkdkjnjsdfnvjbjkfbfjkbdsvjkbdfjvkk j\n"
                            + "vfdbkjhvbdfhjbvjkdfbjsvkbjv fdkjknbjfdjdskfjd\n");
    }//GEN-LAST:event_jLabel5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new telaAjuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
