/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;

/**
 *
 * @author danny
 */
public class telaPagamentos extends javax.swing.JFrame {

    java.awt.event.ActionEvent e;

    /**
     * Creates new form telaClientes
     */
    public telaPagamentos() {
        initComponents();
        jBtCancelarActionPerformed(e);     
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicosPagos = new javax.swing.JTable();
        jLblValorServico = new javax.swing.JLabel();
        jTxtValorServico = new javax.swing.JTextField();
        jBtPagar = new javax.swing.JButton();
        jLblCodCliente1 = new javax.swing.JLabel();
        jTxtCodFactura = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamentos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(780, 570));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Pagamentos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 270, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dinheiro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 60, 70));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 110));

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 40));

        jTableServicosPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableServicosPagos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 760, 220));

        jLblValorServico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblValorServico.setText("Valor:");
        getContentPane().add(jLblValorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 110, 20));

        jTxtValorServico.setEditable(false);
        getContentPane().add(jTxtValorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 270, 30));

        jBtPagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/entrar.png"))); // NOI18N
        jBtPagar.setText("Pagar");
        jBtPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPagarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 40));

        jLblCodCliente1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblCodCliente1.setText("Cod Factura :");
        getContentPane().add(jLblCodCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 110, 20));
        getContentPane().add(jTxtCodFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 270, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Na Totalidade", "Duas Parcelas" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 270, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPagarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBtPagarActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        // TODO add your handling code here:
        jTxtCodFactura.setText("");
        jTxtValorServico.setText("");
        
    }//GEN-LAST:event_jBtCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtPagar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblCodCliente1;
    private javax.swing.JLabel jLblValorServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServicosPagos;
    private javax.swing.JTextField jTxtCodFactura;
    private javax.swing.JTextField jTxtValorServico;
    // End of variables declaration//GEN-END:variables
}
