/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author danny
 */
public class telaFaturacao extends javax.swing.JFrame {
    java.awt.event.ActionEvent e;

    /**
     * Creates new form telaClientes
     */
    public telaFaturacao() {
        initComponents();
        jBtCancelarActionPerformed(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtFactura = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicosPagos = new javax.swing.JTable();
        jLblValorServico = new javax.swing.JLabel();
        jLblCodServico = new javax.swing.JLabel();
        jLblCodCliente = new javax.swing.JLabel();
        jTxtCodCliente = new javax.swing.JTextField();
        jTxtValorServico = new javax.swing.JTextField();
        jLblconsumoServico = new javax.swing.JLabel();
        jTxtConsumoServico = new javax.swing.JTextField();
        jCmbTipoServico = new javax.swing.JComboBox<>();
        jLblValorServico1 = new javax.swing.JLabel();
        jTxtValorServico1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamentos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(850, 570));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Facturacao");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 230, 60));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 60, 80));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 110));

        jBtFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios.png"))); // NOI18N
        jBtFactura.setText("Facturar");
        jBtFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, -1));

        jTableServicosPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableServicosPagos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 760, 190));

        jLblValorServico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblValorServico.setText("Valor:");
        getContentPane().add(jLblValorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 110, 20));

        jLblCodServico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblCodServico.setText("Tipo Servico :");
        getContentPane().add(jLblCodServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, 20));

        jLblCodCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblCodCliente.setText("Cod Cliente :");
        getContentPane().add(jLblCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 110, 20));
        getContentPane().add(jTxtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 330, 30));

        jTxtValorServico.setEditable(false);
        getContentPane().add(jTxtValorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 330, 30));

        jLblconsumoServico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblconsumoServico.setText("Consumo:");
        getContentPane().add(jLblconsumoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, -1));
        getContentPane().add(jTxtConsumoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 330, 30));

        jCmbTipoServico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCmbTipoServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consumo Mensal", "Renovacao do Contrato" }));
        jCmbTipoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbTipoServicoActionPerformed(evt);
            }
        });
        jCmbTipoServico.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCmbTipoServicoPropertyChange(evt);
            }
        });
        getContentPane().add(jCmbTipoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 330, 30));

        jLblValorServico1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblValorServico1.setText("Nome:");
        jLblValorServico1.setEnabled(false);
        getContentPane().add(jLblValorServico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 110, 20));

        jTxtValorServico1.setEditable(false);
        getContentPane().add(jTxtValorServico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 330, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtFacturaActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        // TODO add your handling code here:
        jTxtCodCliente.setText("");
        jCmbTipoServico.setSelectedIndex(0);
        jTxtConsumoServico.setText("");
        jTxtValorServico.setText("");
        jTxtCodCliente.setEditable(true);
        jTxtConsumoServico.setEditable(true);
        jBtFactura.setEnabled(true);
        
        
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jCmbTipoServicoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCmbTipoServicoPropertyChange
      
    }//GEN-LAST:event_jCmbTipoServicoPropertyChange

    private void jCmbTipoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbTipoServicoActionPerformed
        // TODO add your handling code here:
         if(jCmbTipoServico.getSelectedIndex()==1){
          jTxtCodCliente.setEditable(false);
          jTxtConsumoServico.setEditable(false);
          jBtFactura.setEnabled(false);
        }
          if(jCmbTipoServico.getSelectedIndex()==0){
        jTxtCodCliente.setEditable(true);
        jTxtConsumoServico.setEditable(true);
        jBtFactura.setEnabled(true);
        }
    }//GEN-LAST:event_jCmbTipoServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFaturacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFaturacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFaturacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFaturacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new telaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtFactura;
    private javax.swing.JComboBox<String> jCmbTipoServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblCodCliente;
    private javax.swing.JLabel jLblCodServico;
    private javax.swing.JLabel jLblValorServico;
    private javax.swing.JLabel jLblValorServico1;
    private javax.swing.JLabel jLblconsumoServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServicosPagos;
    private javax.swing.JTextField jTxtCodCliente;
    private javax.swing.JTextField jTxtConsumoServico;
    private javax.swing.JTextField jTxtValorServico;
    private javax.swing.JTextField jTxtValorServico1;
    // End of variables declaration//GEN-END:variables
}
