/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import ModeloPercistencia.PercistenciaTaxas;

/**
 *
 * @author danny
 */
public class telaConfiguracoes extends javax.swing.JFrame {

    /**
     * Creates new form telaClientes
     */
    public telaConfiguracoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtSalvar = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jLblCodCliente = new javax.swing.JLabel();
        jTxtTaxaRenovacao = new javax.swing.JTextField();
        jLblCodCliente1 = new javax.swing.JLabel();
        jTxtTaxaNormal1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamentos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 360));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Configurar taxas de Servicos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 300, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 60, 80));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 70));

        jBtSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/entrar.png"))); // NOI18N
        jBtSalvar.setText("Salvar");
        jBtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, -1));

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 40));

        jLblCodCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblCodCliente.setText("Taxa de renovacao:");
        getContentPane().add(jLblCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 180, 20));

        jTxtTaxaRenovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTaxaRenovacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtTaxaRenovacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 240, 30));

        jLblCodCliente1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLblCodCliente1.setText("Taxa de consumo em m3:");
        getContentPane().add(jLblCodCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 220, 20));
        getContentPane().add(jTxtTaxaNormal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalvarActionPerformed
        // TODO add your handling code here:
        double taxaConsumo = Double.parseDouble(jTxtTaxaNormal1.getText());
         double taxaRenovacao = Double.parseDouble(jTxtTaxaRenovacao.getText());
         PercistenciaTaxas.editarDadosTaxas(taxaConsumo,taxaRenovacao);
    }//GEN-LAST:event_jBtSalvarActionPerformed

    private void jTxtTaxaRenovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTaxaRenovacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTaxaRenovacaoActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        // TODO add your handling code here:
        jTxtTaxaNormal1.setText("");
        jTxtTaxaRenovacao.setText("");
        this.dispose();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new telaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblCodCliente;
    private javax.swing.JLabel jLblCodCliente1;
    private javax.swing.JTextField jTxtTaxaNormal1;
    private javax.swing.JTextField jTxtTaxaRenovacao;
    // End of variables declaration//GEN-END:variables
}
